name: flutter4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/gambar/images/Rawon.png
  - assets/gambar/images/LontongBalap.jpeg
  - assets/gambar/images/LontongKupang.jpeg
  - assets/gambar/images/NasiKrawu.jpg
  - assets/gambar/images/PecelMadiun.jpg
  - assets/gambar/images/RujakCingur.jpg
  - assets/gambar/images/SateMadura.jpg
  - assets/gambar/images/SotoLamongan.jpg
  - assets/gambar/images/TahuCampur.jpg
  - assets/gambar/images/TahuTek.jpg
